feat: implement `ruff` as flake checks
Had to add `--impure` to the call due to the following error otherwise:

```
error:
       … while checking flake output 'packages'
         at /nix/store/5cjz7jyqyfr5vq8b6bjs24vdnvdhy9rb-source/flake.nix:118:7:
          117|
          118|       packages = forEachSystem (system:
             |       ^
          119|         let

       … while checking the derivation 'packages.x86_64-linux.bootstrap-aarch64'
         at /nix/store/dg3hg3ksr5sl3adskxiwj7357z47ggvr-source/lib/attrsets.nix:977:47:
          976|   */
          977|   nameValuePair = name: value: { inherit name value; };
             |                                               ^
          978|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: 'builtins.storePath' is not allowed in pure evaluation mode

```